Feat/sidebar2
swsnu/swpp2019-team15 pull request #93
Opened 2019-11-24 17:44 UTC by Minji1234

I made rating system. When you click thumb emoticon it will store and render cool UI.

2019-11-25 06:09 UTC, rachelg98 requested changes
Currently it seems that the user can only rate a single answer to a question. Perhaps it would be nice if the user could rate answers individually  
Additionally, the answer ratings seem to be reset when the page is refreshed

2019-12-01 11:45 UTC, Minji1234 commented
I modified rating in AnswerView. If you click on rate up or rate down emoticon on the AnswerView and refresh the window, it will show your rating has been successfully reflected in the data.
**It shows your rated answer from the bottom position of the screen**

2019-12-01 13:08 UTC, rachelg98 requested changes
Great job! :)
Perhaps it would be nice to display the number of likes and dislikes for each answer and have an Integer field for ratings instead of just a single boolean field. Otherwise an answer can only be rated a single time.

2019-12-01 13:08 UTC, rachelg98 commented on oga/frontend/src/containers/Profile/Profile.js
> +        counts_rating_up: state.rating.rating_up,
These two lines seem to generate an error in the Profile page.

2019-12-03 07:51 UTC, rachelg98 commented on oga/frontend/src/containers/Profile/Profile.js
> +        counts_rating_up: state.rating.rating_up,
Commented out these two lines for now

2019-12-03 13:16 UTC, rachelg98 approved these changes

2019-12-04 14:33 UTC, merged